# Generated by Django 5.2.10 on 2026-06-30 11:16

import core.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sub', models.CharField(blank=True, max_length=255, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid sub. This value may contain only letters, numbers, and @/./+/-/_.', regex='^[\\w.@+-]+\\Z')], verbose_name='sub')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='full name')),
                ('short_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='short name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='identity email address')),
                ('admin_email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='admin email address')),
                ('language', models.CharField(blank=True, choices=[('en-us', 'English'), ('fr-fr', 'Français')], default=None, max_length=10, null=True)),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'slides_user',
            },
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUIDv4, also the Yjs collaboration room name.', primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled presentation', max_length=255)),
                ('content', models.TextField(blank=True, default='', help_text='Optional content snapshot (e.g. base64 Yjs state or JSON). Authoritative live state lives in the collab server.')),
                ('link_role', models.CharField(choices=[('reader', 'Lecture seule'), ('editor', 'Édition')], default='reader', help_text="Access for anyone with the link: 'reader' (read-only) or 'editor'.", max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Nullable: anonymous/local decks have no owner and are world-editable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'presentation',
                'verbose_name_plural': 'presentations',
                'ordering': ['-updated_at'],
            },
        ),
    ]
